services:
  - type: web
    name: moda-gomez
    plan: free
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn webcomic.wsgi --timeout 120"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: surchaing-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: 3.12.10

databases:
  - name: surchaing-db
    plan: free
